### ISSUE TITLE
Search Game Id's Function not working properly

### ISSUE THREAD

**Issue by jestarr** [keberwein/mlbgameday#5]
I just ran a 2017 regular season scrape using the search_gids function.  The last dataset it returns is from September 20th games.

**Comment by keberwein** [comment]
The internal dataset has been updated up to and including the last game of the 2017 World Series, 2017-11-01. Incremental updates will be made throughout the season along when new versions are pushed to CRAN. For now, you can update to the development version by doing a GitHub install.

`devtools::install_github("keberwein/mlbgameday")`
