### ISSUE TITLE
BIS_BOXSCORE Issue

### ISSUE THREAD

**Issue by Djgamelin** [keberwein/mlbgameday#9]
The "gameday_link" returned when using the BIS_BOXSCORE dataset seems to be cut off. 

A typical link/id returned using other datasets has the following format:
gid_X_X_X_Xmlb_Xmlb_X

The Gameday_Link returned is missing the last 5 characters of the normal format, which is a problem for double-headers, which end with _2.

Double-Header Example:
gid_2018_06_19_lanmlb_chnmlb_1
gid_2018_06_19_lanmlb_chnmlb_1
Link in BIS_BOXSCORE --->>>> gid_2018_06_19_lanmlb_chn

**There's no way to differentiate the two games on this date

**Comment by keberwein** [comment]
Thanks for the report. I applied a fix to the issue. You can install the fixed version from GitHub.

`devtools::install_github("keberwein/mlbgameday")`

I probably won't push this to CRAN until the next major release. Working on getting some Statcast data in the mix;)

https://github.com/keberwein/mlbgameday/commit/1ca3581a28015c21afb0fa026bfcb17b13bb02f3

**Comment by Djgamelin** [comment]
Thanks, huge help - really appreciate the fast turnaround! This package is great and Statcast would be a nice addition! Love it.
